# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven dependency analyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Running depdency analyze
      run: (mvn dependency:analyze > analysis.txt | grep -e "Used undeclared dependencies found") && (echo"Failed because of dependency issues";exit 1) || echo "Build passed"
    - name: Checking for used undeclared dependency
      run: (cat analysis.txt | grep -e "Used undeclared dependencies found") && (echo "Failed because of dependency issues";exit 1) || (echo "Build passed";exit 0)
