# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven dependency analyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Running maven dependency analysis plugin
      run: mvn dependency:analyze > analysis.txt
    - name: Checking for used undeclared dependency
      run: (cat analysis.txt | grep -e "Used undeclared dependencies found") && exit 1 || exit 0
